/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.de.uulm.sp.oop;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void alwaysTrue() {
    	assertTrue(true);
    }
}
